Fixing headers
Dog-Finder/mobile pull request #15
Opened 2020-09-21 06:31 UTC by ibutelmann

Added space on Auth screen buttons.
Fixed unnecesary headers.
Added props validation on some screens.
Added placeholder image on lostdogform before selecting image from gallery.
Deleted unnecesary folder (FoudDogItem) with old FoundDogItem.

2020-09-21 12:38 UTC, yoavnavon requested changes
Hace falta arreglar errores de linter

2020-09-21 12:38 UTC, yoavnavon commented on screens/FoundDogListScreen.js
> +  navigation.setOptions({ headerShown: false })
Hay que tratar de setear las opciones de navegación en el navigator correspondiente, no en la logica del componente. Podrías agregar el headerShown  como navigationOption en el HomeBottomTab quizas?

2020-09-21 12:38 UTC, yoavnavon commented on screens/LostDogListScreen.js
> +  navigation.setOptions({ headerShown: false })
Lo mismo que en el otro caso

2020-09-21 12:38 UTC, yoavnavon commented on screens/ShowFoundDogInfoScreen.js
> +  navigation.setOptions({ title: null })
Aca también

2020-09-21 22:26 UTC, ibutelmann commented on screens/FoundDogListScreen.js
> +  navigation.setOptions({ headerShown: false })
Si

2020-09-22 00:50 UTC, yoavnavon approved these changes

2020-09-22 00:50 UTC, merged