Personal publications screen
Dog-Finder/mobile pull request #19
Opened 2021-03-03 08:06 UTC by ibutelmann

Personal publications screen with delete post button.

2021-03-04 01:02 UTC, yoavnavon commented on api/foundDog.js
> +    url: `/found-dog/` + foundId,
Mas limpio
```suggestion
    url: `/found-dog/${foundId}`,
```

2021-03-04 01:03 UTC, yoavnavon commented on api/lostDog.js
> +    url: `/lost-dog/` + lostId,
Lo mismo
```suggestion
    url: `/lost-dog/${lostId}`,
```

2021-03-04 01:05 UTC, yoavnavon commented on navigation/AuthStack.js
> +import AsyncStorage from '@react-native-async-storage/async-storage'
Por que esto? Es lo mismo que lo movieron?

2021-03-04 01:07 UTC, yoavnavon commented on screens/PersonalPublicationsScreen.js
> +  }
Solo sirve para comparar fechas, para que es el `field`? Quizás debiera decir 'date' acá.

2021-03-04 01:11 UTC, yoavnavon commented on screens/ProfileScreen.js
> +  const [createdAt, setcreatedAt] = useState([])
Por que le pasas la lista vacía? Recuerda que ese es el como el value inicial, asi que podria ser un nombre genérico (e.g. `useState('name')`), o puede tener el valor nulo, que creo que sería lo correcto: `useState(null)`.

2021-03-04 01:12 UTC, yoavnavon requested changes
Deje algunos cometarios menores, pero de verdad que se veía todo muy bien!

2021-03-08 04:28 UTC, ibutelmann commented on navigation/AuthStack.js
> +import AsyncStorage from '@react-native-async-storage/async-storage'
Si, la wea tiraba un error que habia que migrarlo a la nueva libreria

2021-03-08 04:29 UTC, ibutelmann commented on screens/PersonalPublicationsScreen.js
> +  }
Si, mejor.

2021-03-08 05:00 UTC, ibutelmann commented on screens/ProfileScreen.js
> +  const [createdAt, setcreatedAt] = useState([])
Cierto!

2021-03-08 13:31 UTC, yoavnavon approved these changes

2021-03-08 19:16 UTC, ibutelmann commented
merging personal publications screen

2021-03-08 19:16 UTC, merged