Personal dog view
Dog-Finder/mobile pull request #8
Opened 2020-07-25 07:21 UTC by ibutelmann

pull request para showfoundoginfo on press.

2020-07-25 17:57 UTC, yoavnavon commented on package.json
> +    "react-native-reanimated": "~1.9.0",
Necesitamos todas estas librerías? Revisa si las usamos sino sacarlas del package.json

2020-07-25 17:58 UTC, yoavnavon commented on redux/store.js
> +  baseURL: ' https://all31gfkx0.execute-api.us-east-1.amazonaws.com/dev',
No sé como te funcionaba, pero hay un espacio antes del `https` que hay que sacar.

2020-07-25 18:01 UTC, yoavnavon requested changes
Esta muy bueno el PR, algunas cosas:
- Resolver los conflictos que tiene con dev
- Eliminar el package-lock, y hacer yarn install
- Ver comentarios individuales que dejé

2020-07-25 18:04 UTC, yoavnavon commented on package.json
> +    "react-native-screens": "~2.9.0",
Estas también

2020-07-26 07:31 UTC, ibutelmann commented on package.json
> +    "react-native-reanimated": "~1.9.0",
el keyboard aware scroll view lo uso en el founddogform que habia hecho antes, es para que cuando se abra el teclado pa escribir el comentario uno pueda ver lo que esta escribiendo y no se bloquee con el teclado.
react native maps y modal datetime picker tambien las usaba en el founddogform que habia hecho.
las otras dos no cacho de donde salieron, las saque del package.json y la app sigue funcionando

2020-07-26 07:32 UTC, ibutelmann commented on redux/store.js
> +  baseURL: ' https://all31gfkx0.execute-api.us-east-1.amazonaws.com/dev',
borra3 el espacio

2020-07-26 07:38 UTC, ibutelmann commented on package.json
> +    "react-native-screens": "~2.9.0",
"react-native-safe-area-context": "~3.0.7" esta la saque, "react-native-screens": "~2.9.0", esta la saque en el comentario anterior, "react-native-scalable-image": "^1.0.0", esta la uso para mostrar la imagen en showfounddoginfoscreen

2020-07-26 22:48 UTC, yoavnavon approved these changes

2020-07-26 22:49 UTC, merged